defaults:
  - model: fc
#  - optimizer: adam
#  - dataset: mnist

seed: 12345
num_epochs: 3
learning_rate: 0.001
batch_size: 64
#in_channels:
#num_features:
#drop_rate:
#num_classes: 10
#data_dir:
#log_dir:
